### model
model_name_or_path: pretrained_models/Muyan-TTS

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: llama-factory/examples/deepspeed/ds_z0_config.json

### dataset
dataset: tts_sft_data
template: llama3
cutoff_len: 2048
max_samples: 10000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: pretrained_models/Muyan-TTS-new-SFT
logging_steps: 10
save_steps: 10000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.01
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 1000
